### ISSUE TITLE
重复执行就尴尬了

### ISSUE THREAD

**Issue by dbing** [ayuayue/hexo2hugo#1]
因某个文件tag 问题，一次执行没通过，再次执行 就很尴尬了~

**Comment by ayuayue** [comment]
是的,现在是存在这个问题,这个版本只是临时用来生成一下,没有做的多么完善,在博客中后面我也有提到,如果最近有时间的话,我会尽快修复,做一下错误的处理以及生成到新的文件夹中去,防止更改原来的文件

**Comment by ayuayue** [comment]
现在已经支持生成到新的文件中了,对于多标签属性的支持还在考虑需不需要
